### ISSUE TITLE
A Quote in Readme.MD is mis-cited

### ISSUE THREAD

**Issue by Miranjunaidi** [Zubi-io/start-here#2]
The Quote "The power of Open Source is the power of the people. The people rule.. " is by Philippe Kahn but it is wrongly mentioned as by Arthur Ashe in the Readme File. The hyperlink is correct and appropriate though. 
![Screenshot 2020-05-20 at 8 18 48 AM](https://user-images.githubusercontent.com/47043997/82399604-26238500-9a73-11ea-8e3f-14ff54c3e24f.png)

**Comment by AllenAJ** [comment]
Fixed. Closing it.

**Comment by Miranjunaidi** [comment]
I think the quote is originally by  Philippe Kahn. The hyperlink was correct but the cited name was wrong.

**Comment by AllenAJ** [comment]
Good observation. Corrected
