### ISSUE TITLE
Youtube link with the quote is not working

### ISSUE THREAD

**Issue by Miranjunaidi** [Zubi-io/start-here#3]
The link corresponding to "work super hard ... every waking hour" by Elon Musk in the Readme.MD redirects to [This youtube link](https://www.youtube.com/watch?v=NU7W7qe2R0A) but the video is unavailable on this link. 
![Screenshot 2020-05-20 at 8 25 56 AM](https://user-images.githubusercontent.com/47043997/82399946-d5f8f280-9a73-11ea-9d13-9e9828b371de.png)

**Comment by Miranjunaidi** [comment]
@AllenAJ This Issue is resolved, right? I see the link has been updated.

**Comment by AllenAJ** [comment]
Yup. Closing it.
